export const profile = {
  name: "Rayan Terki",
  title: "Developpeur IA et application full stack",
  location: "Ottawa-Gatineau",
  availability: "Disponible a distance",
  languages: ["FR", "EN", "AR"],
  email: "rayantrk06@gmail.com",
  github: "https://github.com/rayantr06",
  linkedin: "https://www.linkedin.com/in/rayan-tr-terki-271350318",
  summary: [
    "Je conçois des applications et des systemes IA capables de passer d'une idee floue a une solution concrete, structuree et exploitable.",
    "J'aime travailler sur toute la chaine: analyse du besoin, architecture, developpement full stack, integration des donnees et mise en production.",
    "Mes projets montrent une approche orientee resultat, avec une attention particuliere a la clarte technique, a la qualite du code et a l'utilite reelle pour les utilisateurs.",
  ],
  strengths: [
    "Architecture full stack",
    "Integration IA",
    "APIs et traitement des donnees",
    "Conception d'interfaces",
  ],
  skills: [
    "Python",
    "JavaScript",
    "TypeScript",
    "Next.js",
    "React",
    "FastAPI",
    "Redux Toolkit",
    "SQL",
    "SQLite",
    "Tailwind CSS",
    "Sequelize",
    "Machine Learning",
  ],
};
