export const profile = {
  name: "Rayan Terki",
  title: "Software Developer | Python, C# & TypeScript",
  location: "Canada",
  availability: "Open to backend, full-stack and applied AI roles in Canada",
  languages: ["FR", "EN", "AR"],
  email: "rayantrk06@gmail.com",
  github: "https://github.com/rayantr06",
  linkedin: "https://www.linkedin.com/in/rayan-terki/",
  summary: [
    "I'm a software developer based in Canada. I build web applications, backend APIs and tools that connect data, models and user workflows.",
    "In collaborative projects, my role is software development: connecting services and interfaces, integrating models, and improving application workflows.",
    "I earned an Ontario College Diploma in Computer Programming at Collège La Cité, after completing two years of the integrated preparatory cycle at ESTIN in Béjaïa.",
  ],
  strengths: [
    "Full-stack development",
    "Model integration",
    "Backend APIs",
    "User workflows",
  ],
  skills: [
    "Python",
    "JavaScript",
    "TypeScript",
    "Next.js",
    "React",
    "FastAPI",
    "Redux Toolkit",
    "SQL",
    "SQLite",
    "Tailwind CSS",
    "Sequelize",
    "C#",
    "ASP.NET Core",
    "PostgreSQL",
    "Entity Framework Core",
    "pytest",
    "xUnit",
    "Playwright",
  ],
  skillGroups: [
    { name: "Backend", items: ["Python", "FastAPI", "C#", "ASP.NET Core"] },
    { name: "Frontend", items: ["TypeScript", "JavaScript", "React", "Next.js", "HTML / CSS"] },
    { name: "Data", items: ["SQL", "PostgreSQL", "SQLite", "Entity Framework Core"] },
    { name: "Quality", items: ["pytest", "xUnit", "Playwright", "Integration tests"] },
    { name: "Applied AI", items: ["NLP", "Speech processing", "Model integration"] },
  ],
  education: [
    { school: "Collège La Cité", program: "Computer Programming", credential: "Ontario College Diploma · Earned", dates: "2024–2026" },
    { school: "ESTIN · Béjaïa", program: "Integrated Preparatory Cycle", credential: "Two years · Mathematics and Computer Science", dates: "2021–2023" },
  ],
};
