export function buildProjectSeed() {
  return [
    {
      slug: "lidal-pulse",
      title: "LIDAL Pulse",
      category: "Marketing intelligence",
      shortDescription: "A collaborative marketing intelligence application.",
      fullDescription: "A collaborative marketing intelligence application connecting services, interfaces and multilingual analysis workflows.",
      role: "I connect Python/FastAPI services, React/TypeScript interfaces, multilingual NLP workflows and language-model integration.",
      technologies: "Python, FastAPI, React, TypeScript, NLP",
      githubUrl: "https://github.com/rayantr06/LIDALPulse",
      demoUrl: "",
      imageUrl: "",
    },
    {
      slug: "ouiagent",
      title: "OuiAgent",
      category: "Marketplace",
      shortDescription: "A bilingual marketplace connecting clients with independent security agents.",
      fullDescription: "A bilingual marketplace connecting clients with independent security agents. The application includes agent discovery, booking and account workflows.",
      role: "I contribute to the Next.js/React/TypeScript application, including agent discovery, booking and account workflows.",
      technologies: "Next.js, React, TypeScript",
      githubUrl: "",
      demoUrl: "https://ouiagent.com",
      imageUrl: "",
    },
    {
      slug: "alerte-ia",
      title: "Alerte IA",
      category: "Research prototype",
      shortDescription: "A collaborative emergency-call research prototype with an operator interface.",
      fullDescription: "A collaborative research prototype combining a FastAPI backend and a Next.js/TypeScript frontend. Its operator interface presents transcription and structured incident information.",
      role: "I develop collection and annotation tools, integrate models, and contribute to the operator interface for transcription and structured incident information.",
      technologies: "Python, FastAPI, Next.js, TypeScript, Speech processing",
      githubUrl: "https://github.com/rayantr06/alerte-ia-prototype",
      demoUrl: "",
      imageUrl: "",
    },
    {
      slug: "safar",
      title: "Safar",
      category: "Travel & booking",
      shortDescription: "A collaborative travel and booking platform with client, partner and admin interfaces.",
      fullDescription: "A collaborative travel and booking platform with separate client, partner and admin interfaces.",
      role: "My contributions include authentication routes and fixes to partner booking rendering.",
      technologies: "Next.js, React, TypeScript, Authentication, Booking workflows",
      githubUrl: "https://github.com/rayantr06/safar",
      demoUrl: "",
      imageUrl: "",
    },
    {
      slug: "let-data-dz",
      title: "Let-Data-DZ",
      category: "Audio collection",
      shortDescription: "Browser-based audio collection workflows connected to Drive and Sheets.",
      fullDescription: "Audio collection workflows using HTML/CSS/JavaScript, browser recording and Apps Script integration with Drive and Sheets.",
      role: "I contribute software development for browser recording and audio collection workflows, with Apps Script integration for Drive and Sheets.",
      technologies: "HTML, CSS, JavaScript, Apps Script",
      githubUrl: "",
      demoUrl: "https://let-data-dz.dev",
      imageUrl: "",
    },
    {
      slug: "gestion-tournoi-golf",
      title: "Golf Tournament Management",
      category: "Team application",
      shortDescription: "A team ASP.NET Core MVC application for golf tournament management.",
      fullDescription: "A team application built with ASP.NET Core MVC for golf tournament management.",
      role: "My contributions include interface improvements, database query fixes, integration tests and PostgreSQL deployment adjustments.",
      technologies: "C#, ASP.NET Core MVC, Entity Framework Core, PostgreSQL, Integration tests",
      githubUrl: "https://github.com/khenteurhanane/Gestion_Tournoi_Golf_G06",
      demoUrl: "",
      imageUrl: "",
    },
  ];
}
